
dist: xenial
language: rust
rust:
- nightly
env:
  global:
    - export PATH="$PATH:$HOME/bin"
    - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/lib"
    - export VEGA_LOCAL_IP=0.0.0.0
addons:
  apt:
    packages:
      - gcc
      - g++
install:
  - pip install --user ghp-import
  - curl -O https://capnproto.org/capnproto-c++-0.7.0.tar.gz
  - tar zxf capnproto-c++-0.7.0.tar.gz
  - cd capnproto-c++-0.7.0
  - ./configure --prefix=$HOME
  - make -j3
  - make install
  - cd ../
script:
- cargo build
- for file in $(find user_guide -name '*.md'); do rustdoc --test $file  -L ./target/debug/deps; done
- sed -i 's/ip/0.0.0.0/g' config_files/hosts.conf
- cp config_files/hosts.conf ~/hosts.conf
- cargo doc --no-deps
- cargo test 
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo install mdbook &&
  (cd user_guide; mdbook build) &&
  ghp-import -n user_guide/book &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
